#/bin/bash

CDIR=`pwd`
TMP_FILENAME="/tmp/ckFlacCRC-$$.raw"

echo -n "" > "${CDIR}/dirs.tmp"
find . -mindepth 1 -maxdepth 1 -type d -print0 | xargs -r0 -n 1 echo | cut -c 3- | sort | while read dir ; do
  echo "$dir" >> "${CDIR}/dirs.tmp"
done
cat "${CDIR}/dirs.tmp" | while read dir ; do
  cd "$dir"
  echo "$dir"
  REPORTFILE=`pwd`"/crc32report.txt"
  if [ ! -f "$REPORTFILE" ] ; then
    find . -type f | cut -c3- | sort | while read fn ; do
      if [[ `echo $fn | grep -i \.flac$` ]] ; then
        #rawfn=`echo "$fn" | sed s/.flac/.raw/g`
        flac -d --force-raw-format --endian=little --sign=signed -c "$fn" 2>/dev/null > "${TMP_FILENAME}"
        cfv -q --progress no -C -f "${TMP_FILENAME}.sfv" "${TMP_FILENAME}" 1>/dev/null 2>&1
        rm "${TMP_FILENAME}"
        crc32=`cat "${TMP_FILENAME}.sfv" | grep "${TMP_FILENAME}" | rev | cut -d' ' -f 1 | rev`
        echo "${crc32} ${fn}" >> "${REPORTFILE}"
        rm "${TMP_FILENAME}.sfv"
      fi
    done
  fi
  cd ..
done
rm "${CDIR}/dirs.tmp"
cd "$CDIR"

#flac -d --force-raw-format --endian=little --sign=signed ${FLAC_FILE}
#cfv -C ${RAW_FILE}

#; Generated by cfv v1.18.3 on 2013-06-10 at 14:36.41
#;
#${RAW_FILE} 5a4eed57

#Track  1
#     Filename C:\Stendeck - A Crash Into Another World\Flac\01 Stendeck - Stendeck.wav
#     Pre-gap length  0:00:02.00
#     Peak level 92.4 %
#     Track quality 100.0 %
#     Test CRC 5A4EED57
#     Copy CRC 5A4EED57
#     Accurately ripped (confidence 3)  [283B9EBA]
#     Copy OK
